### ISSUE TITLE
Please add TypeScript types

### ISSUE THREAD

**Issue by emchristiansen** [silane/datetime-js#7]
I'm a fan of the Python datetime package, so I'd like to use this, but I'm using TypeScript.

**Comment by silane** [comment]
Actually, I have never used TypeScript.
I know the benefis of TypeScript but it will take some time to learn it and add type definition to this library.

**Comment by emchristiansen** [comment]
No worries, thanks for the library!
BTW, this (free) book is a great quick intro to TS:
https://basarat.gitbook.io/typescript/

**Comment by silane** [comment]
Thanks for letting me know the book!
I will read the book and add type someday!

**Comment by silane** [comment]
I finally added TypeScript type declarations generated from JSDoc in version 1.3.0.
